wordpress_app:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  volumes:  
    - ./wp_html:/var/www/html
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: CoOlPaSsWoRd
  volumes:
    - ./wp_db:/var/lib/mysql
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: CoOlPaSsWoRd
wp-cli:
  image: ryebell/wp-cli
  volumes_from:
    - wordpress_app
  links:
    - wordpress_db:mysql
  environment:
    WORDPRESS_DB_PASSWORD: CoOlPaSsWoRd
    APACHE_RUN_USER: www-data
