wordpress_app:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 8080:80
  volumes:  
    - ~/wordpress_dev/wp_html:/var/www/html
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: $replace_with_pw
  volumes:
    - ~/wordpress_dev/wp_db:/var/lib/mysql
